
name = "ashara-mubaraka"
compatibility_date = "2024-06-10" # Use a recent, valid date.

# main specifies the entry point to your Worker.
# @cloudflare/next-on-pages generates this file in the .cloudflare directory.
main = ".cloudflare/_worker.js"

[site]
# bucket specifies the directory of static assets to upload.
# @cloudflare/next-on-pages places static assets here.
bucket = ".cloudflare/static"
